### ISSUE TITLE
treemovalGUI.fxml can no longer be loaded into SceneBuilder

### ISSUE THREAD

**Issue by Noah-Schoonover** [Noah-Schoonover/cse326-final-project-treemoval#6]
There must be some issue within the [treemovalGUI.fxml](https://github.com/Noah-Schoonover/cse326-final-project-treemoval/blob/main/src/main/resources/com/treemoval/gui/treemovalGUI.fxml) file.

It could be one of the following issues:
- (_check this first_) the fxml version is not compatible with SceneBuilder (I changed the version manually)
- (_unlikely_) the hierarchy structure is invalid
- (_very likely_) the inclusion of custom classes... SceneBuilder probably doesn't know what to do with ForestScene or ForestGroup.

**Comment by Myles-Willis** [comment]
java.io.IOException: javafx.fxml.LoadException: 
/Users/myleswillis/Documents/GitHub/cse326-final-project-treemoval/src/main/resources/com/treemoval/gui/treemovalGUI.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:101)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:91)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:108)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2560)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:763)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:389)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:665)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenRecent(SceneBuilderApp.java:270)
	at com.oracle.javafx.scenebuilder.app.menubar.MenuBarController.lambda$updateOpenRecentMenuItems$5(MenuBarController.java:1321)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/Users/myleswillis/Documents/GitHub/cse326-final-project-treemoval/src/main/resources/com/treemoval/gui/treemovalGUI.fxml

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.importClass(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.processImport(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.processProcessingInstruction(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:96)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.treemoval.visualizer.ForestScene
	at java.base/java.lang.ClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadTypeForPackage(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadType(Unknown Source)
	... 34 more

**Comment by Myles-Willis** [comment]
The .jar file was imported to Scene Builder to make use of custom classes.
